services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../web:/app
      - /app/node_modules
    ports:
      - "7016:7016"
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    container_name: aigarage-frontend
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:latest
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/html:/usr/share/nginx/html
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    container_name: aigarage-nginx
    depends_on:
      - frontend